In [ ]:
 #numerical python

In [ ]:
from google.colab import drive
drive.mount('/content/drive')


Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
import numpy as np

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv("/content/drive/MyDrive/DATASETS/prueba_categoricas.csv")

In [ ]:
df.head(10)

Nombre  Edad     Género     Ciudad  Ingreso
0     Ana    23   Femenino     Madrid    30000
1    Luis    34  Masculino  Barcelona    40000
2  Carlos    45  Masculino     Madrid    50000
3   Maria    29   Femenino   Valencia    35000
4   Pedro    56  Masculino    Sevilla    60000

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype 
---  ------   --------------  ----- 
 0   Nombre   5 non-null      object
 1   Edad     5 non-null      int64 
 2   Género   5 non-null      object
 3   Ciudad   5 non-null      object
 4   Ingreso  5 non-null      int64 
dtypes: int64(2), object(3)
memory usage: 328.0+ bytes


In [ ]:
#promedio de poblacion de todas las ciudades
df['Ingreso'].mean()

43000.0

In [ ]:
#promedio de visitantes  de todas las ciudades
df['Edad'].mean()

37.4

In [ ]:
np.round(df['Ingreso'].mean()) #Evenly round to the given number of decimals. Redondear uniformemente al número dado de decimales.

43000.0

In [ ]:
df['Edad'].min()

23

In [ ]:
df1 = pd.read_csv("/content/drive/MyDrive/DATASETS/20231205_info_publica_datos_barrios.csv")
df1

id_renabap             nombre_barrio     provincia departamento  \
0              1               Monterrey I  Buenos Aires        Pilar   
1              2               Malvinas II  Buenos Aires     La Plata   
2              3               Ferroviario  Buenos Aires     La Plata   
3              4               La Favelita  Buenos Aires     La Plata   
4              5                    Casaca  Buenos Aires     La Plata   
...          ...                       ...           ...          ...   
6462        6862               Ferroviario       Tucumán    Cruz Alta   
6463        6863            Pacará Pintado       Tucumán    Cruz Alta   
6464        6864             Villa Rosario       Tucumán        Lules   
6465        6865  Ampliación 130 viviendas       Tucumán      Capital   
6466        6866          Virgen Del Valle       Tucumán   Tafí Viejo   

                  localidad  cantidad_viviendas_aproximadas  \
0         Presidente Derqui                              40   
1       José Melchor Romero                             290   
2          Angel Etcheverry                             133   
3                    Tolosa                             122   
4                 City Bell                              20   
...                     ...                             ...   
6462              Las Cejas                             160   
6463             San Andrés                              20   
6464      Ingenio San Pablo                              45   
6465  San Miguel De Tucumán                              19   
6466            Las Talitas                              35   

      cantidad_familias_aproximada decada_de_creacion  anio_de_creacion  \
0                               44        Década 1990               NaN   
1                              319        Década 1990               NaN   
2                              146        Década 2000               NaN   
3                              134        Década 1970               NaN   
4                               22        Década 2000               NaN   
...                            ...                ...               ...   
6462                           176        Década 1920               NaN   
6463                            22        Década 2000               NaN   
6464                            50        Década 1990               NaN   
6465                            21        Década 2010            2014.0   
6466                            39        Década 2010            2016.0   

                                      energia_electrica  \
0         Conexión regular a la red con medidor prepago   
1                           Conexión irregular a la red   
2                           Conexión irregular a la red   
3                           Conexión irregular a la red   
4                           Conexión irregular a la red   
...                                                 ...   
6462                        Conexión irregular a la red   
6463  Conexión formal a la red con medidor domicilia...   
6464  Conexión formal a la red con medidor domicilia...   
6465  Conexión formal a la red con medidor domicilia...   
6466                        Conexión irregular a la red   

                         efluentes_cloacales  \
0      Desagüe a cámara séptica y pozo ciego   
1      Desagüe a cámara séptica y pozo ciego   
2     Desagüe sólo a pozo negro/ciego u hoyo   
3     Desagüe sólo a pozo negro/ciego u hoyo   
4      Desagüe a cámara séptica y pozo ciego   
...                                      ...   
6462   Desagüe a cámara séptica y pozo ciego   
6463  Desagüe sólo a pozo negro/ciego u hoyo   
6464  Desagüe sólo a pozo negro/ciego u hoyo   
6465  Desagüe sólo a pozo negro/ciego u hoyo   
6466  Desagüe sólo a pozo negro/ciego u hoyo   

                                    agua_corriente          cocina  \
0               Bomba de agua de pozo domiciliaria  Gas en garrafa   
1              Conexión irregular a la red de

In [ ]:
fc = df1[df1['nombre_barrio'].isin(['Ferroviario', 'Casaca'])]
#isin verifica si los valores estan contenidos como elementos de la serie/columna nombre_barrio
print(fc.cocina) #del df fc solo veo la columna 'cocina'

2                                    Gas en garrafa
4                                    Gas en garrafa
277                                  Gas en garrafa
650                                  Gas en garrafa
2009    Conexión formal a la red de gas con factura
3963                                 Gas en garrafa
5038                                  Leña o carbón
5290                                 Gas en garrafa
5352                                  Leña o carbón
5379                                 Gas en garrafa
5913    Conexión formal a la red de gas con factura
6462                                 Gas en garrafa
Name: cocina, dtype: object


In [ ]:
print(fc.count()) #cuántos datos hay en total (excluyendo nulos) en una columna o DataFrame

id_renabap                        12
nombre_barrio                     12
provincia                         12
departamento                      12
localidad                         12
cantidad_viviendas_aproximadas    12
cantidad_familias_aproximada      12
decada_de_creacion                12
anio_de_creacion                   2
energia_electrica                 12
efluentes_cloacales               12
agua_corriente                    12
cocina                            12
calefaccion                       12
titulo_propiedad                  12
clasificacion_barrio              12
superficie_m2                     12
dtype: int64


In [ ]:
fc.nombre_barrio.value_counts() #cuántas veces aparece cada valor diferente

nombre_barrio
Ferroviario    11
Casaca          1
Name: count, dtype: int64

In [ ]:
fc.cantidad_familias_aproximada
#en el id n hay x cantidad_familias_aproximada

2       146
4        22
277      33
650     116
2009     40
3963     22
5038     22
5290     17
5352     50
5379     55
5913     44
6462    176
Name: cantidad_familias_aproximada, dtype: int64

In [ ]:
fc['cocina'].value_counts()

cocina
Gas en garrafa                                 8
Conexión formal a la red de gas con factura    2
Leña o carbón                                  2
Name: count, dtype: int64

** ARRAYS **

In [ ]:
#aray
import numpy as np

In [ ]:
#CREACION ARRAY CON NUNPY
my_array = np.array([1,2,3,4,5])
my_array

array([1, 2, 3, 4, 5])

In [ ]:
len(my_array)

5

In [ ]:
my_array.size

5

In [ ]:
#DIMENSIONES DEL ARRAY
my_array.ndim

1

In [ ]:
array_triple = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
array_triple

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [ ]:
print(array_triple)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


EL primer 2 significa 2 bloques (subarrays principales).
El segundo 2 significa 2 filas en cada bloque.
El 3 significa 3 elementos en cada fila.

In [ ]:
array_triple.ndim

3

In [ ]:
#DATA TYPE DEL ARRAY
array_triple.dtype

dtype('int64')

In [ ]:
my_array.shape
#dimenciones y elementos en cada una

(5,)

In [ ]:
array_triple.shape
# dimencion del arreglo

(2, 2, 3)

array_n = np.array([ SUBARRAY A
     [[1,2,3],[4,5,6]], a1- dos array dentro de otro array
     [[7,8,9],[10,11,12],[45,445,554]] a2- tres array dentro de otro array
     ])
 los arrays deben ser rectangulares o regularmente dimensionados


MANIPULACION DE ARRAYS

In [ ]:
#Operaciones

In [ ]:
my_array
print('Array original : ',my_array)

Array original :  [1 2 3 4 5]


In [ ]:
array_nuevo = my_array * 100
print('Array nuevo : ',array_nuevo)

Array nuevo :  [100 200 300 400 500]


In [ ]:
array_veintes = ( [ 21,22,23,24,25])
print('Array veintes : ',array_veintes)

Array veintes :  [21, 22, 23, 24, 25]


In [ ]:
array_nuevo1 = my_array + array_veintes
print('Array nuevo1 : ',array_nuevo1)

Array nuevo1 :  [22 24 26 28 30]


In [ ]:
#CAMBIAR TIIPO DE DATO

a = np.array ([1,2,3])
a.dtype

dtype('int64')

In [ ]:
b = np.array ([1,2,3], dtype=float)
b.dtype

dtype('float64')

In [ ]:
b #cambie a flotando los nros declarados enteros

array([1., 2., 3.])

In [ ]:
c = np.array ([1,0,3], dtype=bool)
c #cambio a booleanos,solo 0 da False

array([ True, False,  True])

In [ ]:
c = np.array ([1,0,3], dtype=complex)
c

array([1.+0.j, 0.+0.j, 3.+0.j])

In [ ]:
#CREACION DE ARRAYS

In [ ]:
#CON RANGO
n = np.arange(10)
n
#VA DEL CERO AL N-1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
#RANGO CON SALTOS
n = np.arange(10,20,2)
n
#10 a 20 de a 2

array([10, 12, 14, 16, 18])

In [ ]:
# ARREGLOS DE ZEROS
n = np.zeros(10)
n

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
n = np.zeros(10, dtype=int)
n

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
#ARREGLOS DE UNOS
n = np.ones(10)
n

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
#ARREGLO A PARTIR E DATOS BASURA
q = np.empty(10)
q
#SIRVE PARA RESERVAR EL ESPACIO EN MEMORIA, LUYEGO PODEMOS MODIFICARLOS

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
#ARREGLOS DE NROS ENTEROS ALEATORIOS
r = np.random.randint(20, size=10)
r

array([10, 10, 12, 18,  8, 19,  6, 16,  3,  6])

In [ ]:
a = np.random.randint(25,30,10)
a
#NROS RANDOM DE X A Y, Z CANT

array([27, 29, 27, 25, 29, 25, 25, 26, 28, 28])

In [ ]:
#MODIFICAR VALORES DESDE EL INDICE
a[0] = 1000
a

array([1000,   29,   27,   25,   29,   25,   25,   26,   28,   28])

In [ ]:
#GENERAR SUB ARREGLOS PARTIENDO DE UN ARREGLO ORIGINAL
# A[START:END:SALTOS]
t = a[1:5]
t

array([29, 27, 25, 29])

In [ ]:
#OMITO DECLARAR EL CERO, SALTO DE 2 EN 2
y = a[:8:2]
y

array([1000,   27,   29,   25])

In [ ]:
#VECTORIZAR
a = np.random.randint(0,10,20)
a

array([0, 8, 8, 5, 1, 8, 4, 9, 9, 0, 4, 0, 6, 9, 0, 5, 8, 6, 3, 0])

In [ ]:
def operacion(valor):
  return (valor + 2) +10

operacion(3)

15

In [ ]:
for valor in a:
  print(operacion(valor))

12
20
20
17
13
20
16
21
21
12
16
12
18
21
12
17
20
18
15
12


In [ ]:
#FUNCION VECTORIZAR PARA CUANDO TENGO MUCHOS VALORES

vector = np.vectorize(operacion) #cre un valor desde los valores que devuelve la funcion operacion
vector (a) #asigno a ese vector (q a su vez se asigna a una funcion) los valores demi array a

array([12, 20, 20, 17, 13, 20, 16, 21, 21, 12, 16, 12, 18, 21, 12, 17, 20,
       18, 15, 12])

In [ ]:
b = np.random.randint(100,150,20)
b

array([109, 119, 129, 112, 142, 138, 107, 128, 126, 120, 137, 142, 100,
       128, 117, 136, 142, 102, 123, 116])

In [ ]:
vector2 = np.vectorize(operacion)
vector2(b)

array([121, 131, 141, 124, 154, 150, 119, 140, 138, 132, 149, 154, 112,
       140, 129, 148, 154, 114, 135, 128])

In [ ]:
#CREO FUNCION LAMBDA (lambda parámetro: OPERACION Q DEVUELVE))
vector3 = np.vectorize(lambda x: x+200)
vector4 =vector3(b) #APLICO LA FUNCION ELEMENTO POR ELEMENTO DE b
vector4

array([309, 319, 329, 312, 342, 338, 307, 328, 326, 320, 337, 342, 300,
       328, 317, 336, 342, 302, 323, 316])

In [ ]:
#CONCATENACION DE ARRAYS

In [ ]:
x =[1,2,3]
y = [4,5,6]
z = [7,8,9]

In [ ]:
juntos = np.concatenate([x,y,z])
juntos

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a =[[1,2,3],[4,5,6]]
b =[[7,8,9],[10,11,12]]
c = [[13,14,15],[16,17,18]]
d = [[19,20,21],[22,23,24]]
e=[[25,26,27],[28,29,30]]

array_concatenado= np.concatenate([a,b,c,d,e], axis=0) #AXIS 1 EJE X, AXIS 0 EJE Y


In [ ]:
print(array_concatenado)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]
 [19 20 21]
 [22 23 24]
 [25 26 27]
 [28 29 30]]


In [175]:
np.concatenate([a,b], axis=0) #axis / eje sobre el cual se ordenan

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [25, 26, 27],
       [28, 29, 30],
       [ 7,  8,  9],
       [10, 11, 12],
       [19, 20, 21],
       [22, 23, 24]])

In [ ]:
a =[[1,2,3],[4,5,6],[25,26,27],[28,29,30]]
b =[[7,8,9],[10,11,12],[19,20,21],[22,23,24]]

np_hor= np.concatenate([a,b], axis=1) #horizontal
np_hor

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12],
       [25, 26, 27, 19, 20, 21],
       [28, 29, 30, 22, 23, 24]])

In [ ]:
np_hor.shape #filas,columnas

(4, 6)

In [ ]:
np_ver=np.concatenate([a,b], axis=0) #horizontal
np_ver

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [25, 26, 27],
       [28, 29, 30],
       [ 7,  8,  9],
       [10, 11, 12],
       [19, 20, 21],
       [22, 23, 24]])

In [ ]:
np_ver.shape #filas, columnasd

(8, 3)

In [ ]:
ar_reshape = np_ver.reshape(3,8)
ar_reshape

array([[ 1,  2,  3,  4,  5,  6, 25, 26],
       [27, 28, 29, 30,  7,  8,  9, 10],
       [11, 12, 19, 20, 21, 22, 23, 24]])

**MANEJO DE NULOS CON NUMPY**

In [180]:
array_nulos = np.array([1,2,3,np.nan,5,np.nan, np.nan,7])
array_nulos

array([ 1.,  2.,  3., nan,  5., nan, nan,  7.])

In [ ]:
#VERIFICA SI HAY NULOS EN EL ARRAY
np.isnan(array_nulos)

array([False, False, False,  True, False, False, False,  True])

In [183]:
np.isnan(array_concatenado).sum()

0

In [ ]:
#PROMEDIO DE ARRAY CON NULOS EN SU INTERIOR
np.mean(array_nulos)

nan

In [ ]:
#PROMEDIO DE ARRAY CONSIDERANDO LS NULOS EN SU INTERIOR, NO CONSIDERA LOS NULOS LOS IGNORA
np.nanmean(array_nulos)

4.0

In [ ]:
#SUSTITUIR VALORES NULOS CON WHERE
array_con_0 = np.where(np.isnan(array_nulos),0,array_nulos)
#condicion, si se cumple reemplazo por esto, sino nos devuelve el valor en ese espacio del array
array_con_0

array([1., 2., 3., 0., 5., 6., 7., 0.])

In [ ]:
promedio_array_con_0 = np.nanmean(array_nulos)
promedio_array_con_0


4.0

In [ ]:
#SUSTITUIR VALORES NULOS CON OTRA VARIABLE
array_con_variable = np.where(np.isnan(array_nulos),promedio_array_con_0 ,array_nulos)
#condicion, si se cumple reemplazo por esto, sino nos devuelve el valor en ese espacio del array
array_con_variable

array([1., 2., 3., 4., 5., 6., 7., 4.])

In [ ]:
#array_filtrado = array_nulos[np.isnan(array_nulos)] me devuelve los nulos.
array_filtrado = array_nulos[~np.isnan(array_nulos)]  #me devuelve los no nulos
array_filtrado
# ~ es como un NOT

array([1., 2., 3., 5., 6., 7.])

In [ ]:
ruta = "/content/drive/MyDrive/Dataa/32.1 medallas.csv"
df_medallas = pd.read_csv(ruta)
df_medallas.head(10)

Oro  Plata  Bronce  Total        Pais
0  NaN    1.0     2.0    3.0   Argentina
1  NaN    2.0     2.0    4.0     Armenia
2   17    7.0    22.0   46.0   Australia
3    1    1.0     5.0    7.0     Austria
4  NaN    3.0     4.0    7.0  Azerbaijan
5    2    NaN     NaN    2.0     Bahamas
6  NaN    1.0     NaN    1.0     Bahrain
7    1    3.0     3.0    7.0     Belarus
8    3    1.0     3.0    7.0     Belgium
9    1    NaN     NaN    1.0     Bermuda

In [ ]:
df_medallas_txt = np.genfromtxt(ruta)
df_medallas_txt
#

ValueError: Some errors were detected !
    Line #15 (got 2 columns instead of 1)
    Line #17 (got 2 columns instead of 1)
    Line #20 (got 2 columns instead of 1)
    Line #22 (got 2 columns instead of 1)
    Line #24 (got 2 columns instead of 1)
    Line #27 (got 4 columns instead of 1)
    Line #36 (got 2 columns instead of 1)
    Line #39 (got 3 columns instead of 1)
    Line #44 (got 4 columns instead of 1)
    Line #63 (got 2 columns instead of 1)
    Line #65 (got 2 columns instead of 1)
    Line #70 (got 2 columns instead of 1)
    Line #72 (got 3 columns instead of 1)
    Line #73 (got 3 columns instead of 1)
    Line #74 (got 4 columns instead of 1)
    Line #77 (got 2 columns instead of 1)
    Line #78 (got 2 columns instead of 1)
    Line #82 (got 2 columns instead of 1)
    Line #86 (got 3 columns instead of 1)

In [ ]:
df_medallas_txt = np.genfromtxt(ruta, delimiter=',') # El delimitador es que separa las columnas
df_medallas_txt

array([[ nan,  nan,  nan,  nan,  nan],
       [ nan,   1.,   2.,   3.,  nan],
       [ nan,   2.,   2.,   4.,  nan],
       [ 17.,   7.,  22.,  46.,  nan],
       [  1.,   1.,   5.,   7.,  nan],
       [ nan,   3.,   4.,   7.,  nan],
       [  2.,  nan,  nan,   2.,  nan],
       [ nan,   1.,  nan,   1.,  nan],
       [  1.,   3.,   3.,   7.,  nan],
       [  3.,   1.,   3.,   7.,  nan],
       [  1.,  nan,  nan,   1.,  nan],
       [ nan,  nan,   1.,   1.,  nan],
       [  7.,   6.,   8.,  21.,  nan],
       [  3.,   1.,   2.,   6.,  nan],
       [ nan,  nan,   1.,   1.,  nan],
       [  7.,   6.,  11.,  24.,  nan],
       [  2.,   4.,   6.,  12.,  nan],
       [ nan,   4.,   1.,   5.,  nan],
       [  3.,   3.,   2.,   8.,  nan],
       [ nan,  nan,   1.,   1.,  nan],
       [  7.,   3.,   5.,  15.,  nan],
       [  4.,   4.,   3.,  11.,  nan],
       [  3.,   4.,   4.,  11.,  nan],
       [ nan,   3.,   2.,   5.,  nan],
       [  2.,   1.,  nan,   3.,  nan],
       [  1.,   1.,   4.,

In [ ]:
df_medallas_txt = np.genfromtxt(ruta, delimiter=',' , filling_values=0)
# El delimitador separa las columnas
#filling values manejar valores faltantes en archivos de texto al cargarlos en un array en este caso reemplazo con 0
df_medallas_txt

array([[  0.,   0.,   0.,   0.,   0.],
       [  0.,   1.,   2.,   3.,   0.],
       [  0.,   2.,   2.,   4.,   0.],
       [ 17.,   7.,  22.,  46.,   0.],
       [  1.,   1.,   5.,   7.,   0.],
       [  0.,   3.,   4.,   7.,   0.],
       [  2.,   0.,   0.,   2.,   0.],
       [  0.,   1.,   0.,   1.,   0.],
       [  1.,   3.,   3.,   7.,   0.],
       [  3.,   1.,   3.,   7.,   0.],
       [  1.,   0.,   0.,   1.,   0.],
       [  0.,   0.,   1.,   1.,   0.],
       [  7.,   6.,   8.,  21.,   0.],
       [  3.,   1.,   2.,   6.,   0.],
       [  0.,   0.,   1.,   1.,   0.],
       [  7.,   6.,  11.,  24.,   0.],
       [  2.,   4.,   6.,  12.,   0.],
       [  0.,   4.,   1.,   5.,   0.],
       [  3.,   3.,   2.,   8.,   0.],
       [  0.,   0.,   1.,   1.,   0.],
       [  7.,   3.,   5.,  15.,   0.],
       [  4.,   4.,   3.,  11.,   0.],
       [  3.,   4.,   4.,  11.,   0.],
       [  0.,   3.,   2.,   5.,   0.],
       [  2.,   1.,   0.,   3.,   0.],
       [  1.,   1.,   4.,

In [ ]:
df_medallas_txt = np.genfromtxt(ruta, delimiter=',', filling_values=0 ,skip_header=1)
#skip_header escapa el enccabezado
df_medallas_txt

array([[  0.,   1.,   2.,   3.,   0.],
       [  0.,   2.,   2.,   4.,   0.],
       [ 17.,   7.,  22.,  46.,   0.],
       [  1.,   1.,   5.,   7.,   0.],
       [  0.,   3.,   4.,   7.,   0.],
       [  2.,   0.,   0.,   2.,   0.],
       [  0.,   1.,   0.,   1.,   0.],
       [  1.,   3.,   3.,   7.,   0.],
       [  3.,   1.,   3.,   7.,   0.],
       [  1.,   0.,   0.,   1.,   0.],
       [  0.,   0.,   1.,   1.,   0.],
       [  7.,   6.,   8.,  21.,   0.],
       [  3.,   1.,   2.,   6.,   0.],
       [  0.,   0.,   1.,   1.,   0.],
       [  7.,   6.,  11.,  24.,   0.],
       [  2.,   4.,   6.,  12.,   0.],
       [  0.,   4.,   1.,   5.,   0.],
       [  3.,   3.,   2.,   8.,   0.],
       [  0.,   0.,   1.,   1.,   0.],
       [  7.,   3.,   5.,  15.,   0.],
       [  4.,   4.,   3.,  11.,   0.],
       [  3.,   4.,   4.,  11.,   0.],
       [  0.,   3.,   2.,   5.,   0.],
       [  2.,   1.,   0.,   3.,   0.],
       [  1.,   1.,   4.,   6.,   0.],
       [ 39.,  41.,  33.,

In [ ]:
df_medallas_txt = np.genfromtxt(ruta, delimiter=',', filling_values=0 ,skip_header=1 , dtype=int)
#skip_header escapa el enccabezado
df_medallas_txt

array([[  0,   1,   2,   3,   0],
       [  0,   2,   2,   4,   0],
       [ 17,   7,  22,  46,   0],
       [  1,   1,   5,   7,   0],
       [  0,   3,   4,   7,   0],
       [  2,   0,   0,   2,   0],
       [  0,   1,   0,   1,   0],
       [  1,   3,   3,   7,   0],
       [  3,   1,   3,   7,   0],
       [  1,   0,   0,   1,   0],
       [  0,   0,   1,   1,   0],
       [  7,   6,   8,  21,   0],
       [  3,   1,   2,   6,   0],
       [  0,   0,   1,   1,   0],
       [  7,   6,  11,  24,   0],
       [  2,   4,   6,  12,   0],
       [  0,   4,   1,   5,   0],
       [  3,   3,   2,   8,   0],
       [  0,   0,   1,   1,   0],
       [  7,   3,   5,  15,   0],
       [  4,   4,   3,  11,   0],
       [  3,   4,   4,  11,   0],
       [  0,   3,   2,   5,   0],
       [  2,   1,   0,   3,   0],
       [  1,   1,   4,   6,   0],
       [ 39,  41,  33, 113,   0],
       [  1,   0,   1,   2,   0],
       [  1,   1,   2,   4,   0],
       [  1,   0,   1,   2,   0],
       [  0,  

EXPORTACION DE DATOS CON NP

In [ ]:
array_ejemplo = np.array([[1,2,3],[4,5,6]])
array_ejemplo

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
ruta_salida = "/content/drive/MyDrive/Dataa/array_ejemplo.csv"
np.savetxt(ruta_salida, array_ejemplo, delimiter=',', fmt="%d")
#ruta, array a guardar, tipo de delimitador
#fmt  especificar el formato en el que se guardarán los valores en un archivo de texto
ruta_salida

'/content/drive/MyDrive/Dataa/array_ejemplo.csv'

INTEGRACION NUMPY Y PANDAS

In [ ]:
df_practica = pd.DataFrame(
    {
        'Impares': [3,5,9],
        'Pares': [2,4,6]
    }
)
df_practica

Impares  Pares
0        3      2
1        5      4
2        9      6

In [ ]:
df_practica.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Impares  3 non-null      int64
 1   Pares    3 non-null      int64
dtypes: int64(2)
memory usage: 176.0 bytes


In [ ]:
#DF A ARRAY DE NUMPY
#ceo un array basandome en los valores de un DF
array_np1 = df_practica.values
array_np1

array([[3, 2],
       [5, 4],
       [9, 6]])

In [ ]:
array2 = df_practica.to_numpy()
array2

array([[3, 2],
       [5, 4],
       [9, 6]])

In [ ]:
#operaciones de numpy en DF pandas
df_practica

Impares  Pares
0        3      2
1        5      4
2        9      6

In [ ]:
np.sqrt(df_practica) #sqrt es un metodo de np raiz cuadrada

Impares     Pares
0  1.732051  1.414214
1  2.236068  2.000000
2  3.000000  2.449490

In [ ]:
np.mean(df_practica)

4.833333333333333

In [ ]:
arr_dos_columnas_random = np.random.randint(2,9,(2,4)) #2 filas, 4 columnas
arr_dos_columnas_random

array([[5, 6, 2, 6],
       [7, 4, 4, 7]])

In [ ]:
df_desde_np = pd.DataFrame(arr_dos_columnas_random, columns=['Col1', 'Col2', 'Col3', 'Col4'])
df_desde_np

Col1  Col2  Col3  Col4
0     5     6     2     6
1     7     4     4     7